name: Andrii Panasiuk
url: http://andriipanasiuk.com
destination: ./_site
lsi: false
port: 4000
highlighter: pygments
markdown: kramdown
kramdown:
  parse_block_html: true
permalink: pretty
#paginate: 5
gems:
  - jekyll-sitemap

exclude:
  - .travis.yml
  - validate.rb
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
